name: Seed Assets to Database

on:
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for running the seed'
        required: true
        default: 'Initial asset seeding'

jobs:
  seed:
    runs-on: ubuntu-latest
    name: Load Assets to Supabase
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
          cache-dependency-path: 'apps/etl/requirements.txt'

      - name: Install dependencies
        run: pip install -r apps/etl/requirements.txt
      
      - name: Run Seeder
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        run: |
          python apps/etl/src/seed.py 